In [41]:
import scipy.linalg as sp
import numpy as np

In [42]:
a = np.array([[1, -2, 3],
 [4, 5, 6],
 [7, 1, 9]])

In [43]:
b = np.array([1, 2, 3])

In [47]:
x = sp.solve(a,b)

In [48]:
a

array([[ 1, -2,  3],
       [ 4,  5,  6],
       [ 7,  1,  9]])

In [49]:
b

array([1, 2, 3])

In [50]:
a@x

array([1., 2., 3.])

In [51]:
B = np.random.rand(3,3)

In [52]:
B

array([[0.21819304, 0.64319599, 0.92159693],
       [0.54698198, 0.03884771, 0.39080884],
       [0.45345573, 0.50453189, 0.33246663]])

In [53]:
X = sp.solve(a,B)

In [54]:
a@X

array([[0.21819304, 0.64319599, 0.92159693],
       [0.54698198, 0.03884771, 0.39080884],
       [0.45345573, 0.50453189, 0.33246663]])

In [55]:
val, vec = sp.eig(a)

In [56]:
val

array([-1.13261772+0.j, 10.67269524+0.j,  5.45992248+0.j])

In [57]:
vec

array([[-0.8215735 ,  0.05324273,  0.25636602],
       [-0.02150583,  0.74309552, -0.93563185],
       [ 0.56969684,  0.66706391, -0.24263037]])

In [58]:
sp.inv(a)

array([[-0.59090909, -0.31818182,  0.40909091],
       [-0.09090909,  0.18181818, -0.09090909],
       [ 0.46969697,  0.22727273, -0.1969697 ]])

In [59]:
sp.det(a)

np.float64(-66.0)

In [60]:
sp.norm(a)

np.float64(14.89966442575134)